### ISSUE TITLE
Preserve point position when formatting

### ISSUE THREAD

**Issue by Wilfred** [fbergroth/emacs-rustfmt#6]
Suppose I have the following code, where | is the point:

``` rust
fn foo(foo_bar_baz1: i32, foo_bar_baz2: i32, foo_bar_baz3: i32, foo_bar_baz4: i32, foo_bar_baz5: i32, foo_bar_baz6: i32) {

}

fn bar() {|}
```

Calling `rustfmt-format-buffer` replaces the whole buffer, and leaves point on the same line number. As a I result, I get:

``` rust
fn foo(foo_bar_baz1: i32,
       foo_bar_baz2: i32,
       foo_bar_baz3: i32,
       foo_bar_baz4: i32,
       foo_bar_baz5: i32,
       foo_b|ar_baz6: i32) {

}

fn bar() {}
```

Rustfmt has `--write-mode=diff` so emacs-rustfmt could just apply the diff. Emacs' markers are smart enough to move if text is inserted before them. This is how [gofmt is integrated with Emacs](https://github.com/dominikh/go-mode.el/blob/5d53a13bd193653728e74102c81aa931b780c9a9/go-mode.el#L934).

**Comment by fbergroth** [comment]
That would be great! Unfortunately [it seems rustfmt](https://github.com/rust-lang-nursery/rustfmt/blob/34737529db58b041f46ff25c37ef47c57553038e/src/bin/rustfmt.rs#L188) don't support it when reading from stdin.  :disappointed:

**Comment by Wilfred** [comment]
Moved to https://github.com/rust-lang/rust-mode/issues/162
